global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus kendi metrikleri
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Pong Game Backend metrikleri
  - job_name: 'pong-backend'
    static_configs:
      - targets: ['backend:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 5s
