global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'pong-backend'
    static_configs:
      - targets: ['nginx:443']
    metrics_path: '/api/metrics'
    scrape_interval: 5s
    scheme: https
    tls_config:
      insecure_skip_verify: true
