global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus kendi metrikleri
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Pong Game Backend metrikleri
  - job_name: 'pong-backend'
    static_configs:
      - targets: ['backend:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 5s

  # Nginx metrikleri (nginx-prometheus-exporter gerekebilir)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/health'
    scrape_interval: 30s

  # Node Exporter (sistem metrikleri için - isteğe bağlı)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s