global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - "/etc/prometheus/alerts.yml"

scrape_configs:
  - job_name: 'pong-backend'
    static_configs:
      - targets: ['nginx:443']
    metrics_path: '/api/metrics'
    scrape_interval: 5s
    scheme: https
    tls_config:
      insecure_skip_verify: true

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s
